### ISSUE TITLE
Web.Api: Reviewer page

### ISSUE THREAD

**Issue by komdil** [srp-internships/MRA-Jobs#151]
Manage Vacancies: 

**Categories:** 

**Get:** api/categories
**Payload:** Name

**POST:** api/categories
**Payload:** Name,

**PUT:** api/categories{slug}
**Payload:** Name

**Trainings:** 
**POST:** api/tranings
**Payload:** CategoryId, Title, Description, ShortDescription, Questions[] , DeadLine

**PUT:** api/tranings{slug}
**Payload:** CategoryId, Title, Description, ShortDescription, Questions[] ,DeadLine
 
**Jobs:** 
**POST:** api/jobs
**Payload:** CategoryId, Title, Description, ShortDescription, Questions[] ,DeadLine, YearOfExperience

**PUT:** api/jobs{slug}
**Payload:** CategoryId, Title, Description, ShortDescription, Questions[] , YearOfExperience

**Intrenships:** 
**POST:** api/internships
**Payload:** CategoryId, Title, Description, ShortDescription, Questions[] ,DeadLine, Duration, Payable

**PUT:** api/internships{slug}
**Payload:** CategoryId, Title, Description, ShortDescription, Questions[] ,DeadLine, Duration, Payable

Most of them already implemented, Make sure that everything works, Add Integration Tests

**Comment by Muhammadislom99** [comment]
![image](https://github.com/srp-internships/MRA-Jobs/assets/108611175/e60d04cb-c8f5-490d-841d-8385992ab90f)
I think this method shoild return slug ....

**Comment by Muhammadislom99** [comment]
![image](https://github.com/srp-internships/MRA-Jobs/assets/108611175/c0922b6a-6c0c-49ab-839c-cc386892ebc8)
slug is not unique

**Comment by Muhammadislom99** [comment]
![image](https://github.com/srp-internships/MRA-Jobs/assets/108611175/c2a8dfcc-4f1f-406e-a481-744c745a257b)
![image](https://github.com/srp-internships/MRA-Jobs/assets/108611175/0ca405d3-89ac-42d7-bf1c-57d9f82f0064)
I think the slug don't should updated
