### ISSUE TITLE
Application.Tests:Create tests for get method in jobs controller

### ISSUE THREAD

**Issue by Firuz2006** [srp-internships/MRA-Jobs#229]
Add 1 or more Internship vacancies;
Add 1 or more job vacancies;
check quantity of job vacancies;
Create tests for get by slug

**Comment by Firuz2006** [comment]
tests will pass without authorization

**Comment by Muhammadislom99** [comment]
@Firuz2006 Why "Add 1 or more Internship vacancies"?
